version: '3.8'

services:
  e-commerce-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/ecommerceDb
      - spring.datasource.username=root
      - spring.datasource.password=root123456